//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 SupermarketPurchaseAndSalesManagementSystem.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_SupermarketPurchaseAndSalesManagementSystemTYPE 130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDI_ICON_RE                     310
#define IDI_ICON_WIN                    311
#define IDD_CDispalyView                312
#define IDD_DIALOG1                     322
#define IDD_DIALOG_LOGIN                322
#define DIALOG_LOGIN                    322
#define IDB_BITMAP14                    343
#define DIALOG_USER                     344
#define DIALOG_SELL                     346
#define DIALOG_INFO                     350
#define CAddDlg                         352
#define IDB_BITMAP_LOGIN                354
#define DIALOG_ADD                      355
#define DIALOG_DEL                      357
#define DIALOG_REGISTER                 362
#define DIALOG_IO_TAB                   365
#define DIALOG_INPUT                    367
#define DIALOG_OUTPUT                   368
#define DIALOG_CHANGE_PWD               369
#define IDB_BITMAP_REGISTER             372
#define DIALOG_SAFETY_SYS               375
#define DIALOG_FIRM_TAB                 376
#define IDB_BITMAP_USER_CAPTION         377
#define DIALOG_FIRM_INF                 377
#define IDB_BITMAP_USER                 378
#define DIALOG_FIRM_ADMIN               378
#define DIALOG_ADD_STAFF                379
#define IDB_BITMAP_ABOUT                380
#define DIALOG_SELL_MULTIPLE            380
#define IDB_BITMAP_SELL_BACKGROUND      381
#define DIALOG_PRODUCT_INFO             381
#define IDI_ICON_INPUT                  383
#define IDI_ICON_OUTPUT                 384
#define IDI_ICON_USER                   385
#define IDI_ICON2                       386
#define IDI_ICON_INFO                   386
#define IDI_ICON1                       387
#define IDI_ICON_SELL                   387
#define IDI_ICON3                       388
#define IDI_ICON_RECORD                 388
#define DIALOG_WARN_STOCK               391
#define DIALOG_FORGOT_PWD               392
#define DIALOG_USER_STAFF               393
#define DIALOG_CHANGE_SAFETY            394
#define IDB_BITMAP_USER_CAPTION_FIX     394
#define DIALOG_CHANGE_STAFF             395
#define DIALOG_FIRM_ADD                 396
#define DIALOG_SET_SAFETY               397
#define IDB_BITMAP_SCHOOL_BADGE         398
#define DIALOG_CHANGE_PRODUCT           398
#define IDI_ICON4                       399
#define IDI_ICON_SCHOOL_BADGE           399
#define DIALOG_CHANGE_FIRM              399
#define IDC_EDIT1                       1002
#define IDC_EDIT2                       1003
#define IDC_BUTTON1                     1004
#define IDC_EDIT3                       1004
#define IDC_BUTTON2                     1005
#define IDC_EDIT5                       1005
#define IDC_REGISTER                    1006
#define IDC_BUTTON3                     1006
#define IDC_EDIT6                       1006
#define IDC_CHANGE_PWD                  1007
#define IDC_COMBO1                      1007
#define IDC_BUTTON_OK2                  1007
#define IDC_EDIT4                       1008
#define IDC_BUTTON10                    1008
#define IDC_BUTTON8                     1009
#define IDC_EDIT7                       1009
#define IDC_EDIT_OUT_PRICE2             1009
#define IDC_EDIT_SAFETY                 1009
#define IDC_BUTTON_DEL                  1009
#define IDC_BUTTON9                     1010
#define IDC_EDIT8                       1010
#define IDC_EDIT_KIND                   1010
#define IDC_EDIT_ID2                    1010
#define IDC_LIST1                       1011
#define IDC_EDIT9                       1011
#define IDC_EDIT_FIRMID                 1011
#define IDC_EDIT_ANS2                   1011
#define IDC_COMBO2                      1012
#define IDC_COMBO_NAME2                 1012
#define IDC_LIST2                       1012
#define IDC_BUTTON4                     1013
#define IDC_BUTTON5                     1014
#define IDC_BUTTON6                     1015
#define IDC_BUTTON7                     1016
#define IDC_TABCTRL                     1018
#define IDC_STATIC_PIC                  1022
#define IDC_STATIC_GROUP                1023
#define IDC_STATIC_CAPTION              1024
#define IDC_STATIC_GROUP3               1024
#define IDC_STATIC_GROUP1               1025
#define IDC_STATIC_GROUP2               1026
#define IDC_EDIT_IN_PRICE1              1028
#define IDC_EDIT_IN_PRICE2              1030
#define IDC_LIST3                       1032
#define IDC_EDIT_USER                   1033
#define IDC_EDIT_PWD                    1034
#define IDC_EDIT_RPWD                   1035
#define IDC_EDIT_NEWPWD                 1036
#define IDC_EDIT_RNEWPWD                1037
#define IDC_EDIT_ID                     1038
#define IDC_EDIT_OLDANS                 1039
#define IDC_EDIT_ANS                    1040
#define IDC_EDIT_FAX                    1040
#define IDC_COMBO_SAFETY                1041
#define IDC_BUTTON_OK1                  1042
#define IDC_BUTTON_CANCEL1              1043
#define IDC_BUTTON_CANCEL2              1044
#define IDC_COMBO_STAFF                 1045
#define IDC_EDIT_STAFF_ID               1046
#define IDC_BUTTON_CHANGE_STAFF         1047
#define IDC_BUTTON_DEL_STAFF            1048
#define IDC_BUTTON_FIND_STAFF           1049
#define IDC_COMBO_JURISIDICTION         1050
#define IDC_EDIT_STAFF_NAME             1051
#define IDC_EDIT_STAFF_USER             1052
#define IDC_EDIT_STAFF_PWD              1053
#define IDC_COMBO_JURISIDICTION2        1054
#define IDC_EDIT_STAFF_NAME2            1055
#define IDC_EDIT_STAFF_USER2            1056
#define IDC_EDIT_STAFF_PWD2             1057
#define IDC_BUTTON_CHANGE               1058
#define IDC_BUTTON_CANCEL               1059
#define IDC_COMBO_STAFF_NAME            1060
#define IDC_EDIT_NAME                   1061
#define IDC_EDIT_STAFF_JURISIDICTION    1061
#define IDC_COMBO_NAME1                 1062
#define IDC_EDIT_ADDRESS                1062
#define IDC_BUTTON_FIND                 1063
#define IDC_EDIT_PHONENUMBER            1063
#define IDC_BUTTON_PUT                  1064
#define IDC_BUTTON_DOWN                 1065
#define IDC_BUTTON_DOWN_ALL             1066
#define IDC_COMBO_NAME                  1067
#define IDC_BUTTON_PUT_ALL              1067
#define IDC_EDIT_INFO                   1068
#define IDC_BUTTON_ADD                  1069
#define IDC_BUTTON_RESET                1070
#define IDC_BUTTON_ALL_SELL             1071
#define IDC_EDIT_JURISDICTION           1072
#define IDC_BUTTON_CHANGE_LOGIN         1073
#define IDC_BUTTON_FIRM_FIND            1074
#define IDC_BUTTON_FIRM_RESET           1075
#define IDC_EDIT_IN_PRICE               1078
#define IDC_EDIT_OUT_PRICE              1079
#define IDC_EDIT_NUM                    1080
#define IDC_EDIT_IN_NAME                1081
#define IDC_EDIT_PHONE                  1082
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_32779                        32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        400
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
